[package]
name = "dowe_agent"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
dowe_agent_harness = { path = "../agent_harness" }
dowe_codegraph = { path = "../codegraph" }
dowe_stdlib = { path = "../stdlib" }
dowe_runtime = { path = "../runtime" }
rand_core.workspace = true
reqwest.workspace = true
png = "0.18.1"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
dowe_compiler = { path = "../compiler" }
dowe_components = { path = "../components" }
tempfile = "3.23.0"

[lib]
path = "src/lib.rs"
