include!("structure_shell_nodes.rs");
include!("structure_layout_nodes.rs");
include!("structure_content_nodes.rs");

fn render_swift_structure_node(
    node: &ViewNode,
    indent: usize,
    output: &mut String,
    flow: NativeFlow,
    inherited_font: Option<&ResponsiveValue<FontFamily>>,
    default_family: FontFamily,
    context: &SwiftReactiveContext,
) {
    match node {
        ViewNode::Splash { .. } => render_swift_structure_splash(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Scope { .. } => render_swift_structure_scope(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Each { .. } => render_swift_structure_each(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Box { .. } => render_swift_structure_box(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Section { .. } => render_swift_structure_section(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Flex { .. } => render_swift_structure_flex(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Grid { .. } => render_swift_structure_grid(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Card { .. } => render_swift_structure_card(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Brand { .. } => render_swift_structure_brand(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Banner { .. } => render_swift_structure_banner(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        ViewNode::Children => render_swift_structure_children(
            node,
            indent,
            output,
            flow,
            inherited_font,
            default_family,
            context,
        ),
        _ => unreachable!(),
    }
}
