[package]
name = "dowe_runtime"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
default = []
candle = ["dowe_inference/candle"]

[dependencies]
axum.workspace = true
axum-server.workspace = true
argon2.workspace = true
base64.workspace = true
bytes.workspace = true
dowe_ai = { path = "../ai" }
dowe_components = { path = "../components" }
dowe_compiler = { path = "../compiler" }
dowe_crypto = { path = "../crypto" }
dowe_cache = { path = "../cache" }
dowe_queue = { path = "../queue" }
dowe_inference = { path = "../inference" }
dowe_id = { path = "../id" }
dowe_spawn = { path = "../spawn" }
dowe_stdlib = { path = "../stdlib" }
dowe_database = { path = "../database" }
dowe_vector = { path = "../vector" }
futures-util.workspace = true
notify.workspace = true
reqwest.workspace = true
rcgen.workspace = true
rustls-acme.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tower-http.workspace = true
tempfile = "3.23.0"

[target.'cfg(target_os = "linux")'.dependencies]
libloading.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
webview2-com = "0.39.1"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tokio-tungstenite.workspace = true

[lib]
path = "src/lib.rs"
