[package]
name = "dowe_deploy"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
dowe_compiler = { path = "../compiler" }
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
rand_core.workspace = true
sha2.workspace = true
sha1.workspace = true
flate2 = "1"
tar = "0.4"
tempfile = "3.23.0"
wasm-encoder = "0.244.0"

[dev-dependencies]
wasmparser = "0.244.0"
tokio.workspace = true

[lib]
path = "src/lib.rs"
