use super::super::*;
use wasm_encoder::{BlockType, Function, MemArg, ValType};

pub(super) fn memory_arg() -> MemArg {
    MemArg {
        offset: 0,
        align: 0,
        memory_index: 0,
    }
}

pub(super) fn bytes_equal_function() -> Function {
    let mut function = Function::new([(1, ValType::I32)]);
    let mut instructions = function.instructions();
    instructions
        .i32_const(0)
        .local_set(4)
        .block(BlockType::Empty)
        .loop_(BlockType::Empty)
        .local_get(4)
        .local_get(1)
        .i32_ge_u()
        .br_if(1)
        .local_get(0)
        .local_get(4)
        .i32_add()
        .i32_load8_u(memory_arg())
        .local_get(2)
        .local_get(4)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_ne()
        .if_(BlockType::Empty)
        .i32_const(0)
        .return_()
        .end()
        .local_get(4)
        .i32_const(1)
        .i32_add()
        .local_set(4)
        .br(0)
        .end()
        .end()
        .i32_const(1)
        .end();
    function
}

pub(super) fn find_slash_function() -> Function {
    let mut function = Function::new([(1, ValType::I32)]);
    let mut instructions = function.instructions();
    instructions
        .local_get(2)
        .local_set(3)
        .block(BlockType::Empty)
        .loop_(BlockType::Empty)
        .local_get(3)
        .local_get(1)
        .i32_ge_u()
        .br_if(1)
        .local_get(0)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_const(b'/' as i32)
        .i32_eq()
        .br_if(1)
        .local_get(3)
        .i32_const(1)
        .i32_add()
        .local_set(3)
        .br(0)
        .end()
        .end()
        .local_get(3)
        .end();
    function
}

pub(super) fn copy_bytes_function() -> Function {
    let mut function = Function::new([(1, ValType::I32)]);
    let mut instructions = function.instructions();
    instructions
        .i32_const(0)
        .local_set(3)
        .block(BlockType::Empty)
        .loop_(BlockType::Empty)
        .local_get(3)
        .local_get(2)
        .i32_ge_u()
        .br_if(1)
        .local_get(0)
        .local_get(3)
        .i32_add()
        .local_get(1)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_store8(memory_arg())
        .local_get(3)
        .i32_const(1)
        .i32_add()
        .local_set(3)
        .br(0)
        .end()
        .end()
        .end();
    function
}

pub(super) fn render_created_json_function(prefix: Blob) -> Function {
    let mut function = Function::new([(4, ValType::I32)]);
    let mut instructions = function.instructions();
    instructions
        .local_get(1)
        .i32_const(2)
        .i32_lt_u()
        .if_(BlockType::Empty)
        .i32_const(-1)
        .return_()
        .end()
        .local_get(0)
        .i32_load8_u(memory_arg())
        .i32_const(b'{' as i32)
        .i32_ne()
        .if_(BlockType::Empty)
        .i32_const(-1)
        .return_()
        .end()
        .local_get(0)
        .local_get(1)
        .i32_add()
        .i32_const(1)
        .i32_sub()
        .i32_load8_u(memory_arg())
        .i32_const(b'}' as i32)
        .i32_ne()
        .if_(BlockType::Empty)
        .i32_const(-1)
        .return_()
        .end()
        .local_get(0)
        .i32_const(1)
        .i32_add()
        .local_set(3)
        .local_get(0)
        .local_get(1)
        .i32_add()
        .i32_const(1)
        .i32_sub()
        .local_set(4)
        .i32_const(0)
        .local_set(5)
        .block(BlockType::Empty)
        .loop_(BlockType::Empty)
        .local_get(3)
        .local_get(4)
        .i32_ge_u()
        .br_if(1)
        .local_get(0)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_const(32)
        .i32_ne()
        .local_get(0)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_const(9)
        .i32_ne()
        .i32_and()
        .local_get(0)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_const(10)
        .i32_ne()
        .i32_and()
        .local_get(0)
        .local_get(3)
        .i32_add()
        .i32_load8_u(memory_arg())
        .i32_const(13)
        .i32_ne()
        .i32_and()
        .if_(BlockType::Empty)
        .i32_const(1)
        .local_set(5)
        .end()
        .local_get(3)
        .i32_const(1)
        .i32_add()
        .local_set(3)
        .br(0)
        .end()
        .end()
        .local_get(2)
        .i32_const(prefix.pointer as i32)
        .i32_const(prefix.length as i32)
        .call(COPY_BYTES_FUNCTION)
        .local_get(2)
        .i32_const(prefix.length as i32)
        .i32_add()
        .local_set(6)
        .local_get(5)
        .if_(BlockType::Empty)
        .local_get(6)
        .i32_const(b',' as i32)
        .i32_store8(memory_arg())
        .local_get(6)
        .i32_const(1)
        .i32_add()
        .local_set(6)
        .local_get(6)
        .local_get(0)
        .i32_const(1)
        .i32_add()
        .local_get(1)
        .i32_const(2)
        .i32_sub()
        .call(COPY_BYTES_FUNCTION)
        .local_get(6)
        .local_get(1)
        .i32_const(2)
        .i32_sub()
        .i32_add()
        .local_set(6)
        .end()
        .local_get(6)
        .i32_const(b'}' as i32)
        .i32_store8(memory_arg())
        .local_get(6)
        .i32_const(1)
        .i32_add()
        .local_set(6)
        .local_get(6)
        .local_get(2)
        .i32_sub()
        .end();
    function
}
