include!("core_generation_foundations.rs");
include!("core_generation_layout_fixtures.rs");
include!("core_generation_runtime.rs");
include!("core_generation_text.rs");
include!("core_generation_layout.rs");
include!("core_generation_variants.rs");
include!("core_generation_reuse.rs");
include!("core_generation_responsive.rs");
include!("core_generation_metadata.rs");
