[package]
name = "dowe_queue"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
dowe_id = { path = "../id" }
futures-util.workspace = true
lapin.workspace = true
rand_core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true

[dev-dependencies]
rcgen.workspace = true
rustls = "0.23.40"
tempfile = "3.23.0"
tokio-rustls = "0.26.4"

[lib]
path = "src/lib.rs"
