fn marketing_block_rules() -> impl Iterator<Item = (&'static str, &'static [&'static str])> {
    [
        (
            "views/blocks",
            &[
                "block",
                "blocks",
                "bloque",
                "bloques",
                "pattern",
                "patterns",
                "patrón",
                "patrones",
                "recipe",
                "recipes",
                "receta",
                "recetas",
                "section",
                "sections",
                "sección",
                "secciones",
            ] as &[_],
        ),
        (
            "views/blocks/hero",
            &[
                "hero",
                "headline",
                "landing hero",
                "hero dividido",
                "hero editorial",
            ],
        ),
        (
            "views/blocks/metrics",
            &[
                "metric",
                "metrics",
                "metricas",
                "métricas",
                "stats",
                "proof",
                "estadísticas",
                "indicadores",
            ],
        ),
        (
            "views/blocks/split-media",
            &[
                "split media",
                "media split",
                "ecosystem",
                "ecosistema",
                "capabilities",
                "capacidades",
                "imagen lateral",
                "texto e imagen",
            ],
        ),
        (
            "views/blocks/opportunity",
            &[
                "opportunity",
                "oportunidad",
                "genesis",
                "dark band",
                "banda oscura",
                "launch",
                "lanzamiento",
            ],
        ),
        (
            "views/blocks/growth",
            &[
                "growth",
                "crecimiento",
                "utility",
                "utilidad",
                "adoption",
                "adopción",
                "roadmap",
                "progreso",
            ],
        ),
        (
            "views/blocks/cta",
            &[
                "cta",
                "call to action",
                "llamada a la acción",
                "white paper",
                "construyamos juntos",
                "media panel",
            ],
        ),
        (
            "views/blocks/faq",
            &[
                "faq",
                "frequently asked",
                "questions",
                "preguntas frecuentes",
                "dudas",
                "accordion",
            ],
        ),
        (
            "views/blocks/contact",
            &[
                "contact",
                "contacto",
                "reach out",
                "habla con nosotros",
                "channels",
                "canales",
            ],
        ),
    ]
    .into_iter()
}
