fn signature_text(namespace: &str, function: &str) -> Option<StdlibSignature> {
    let signature = match (namespace, function) {
        ("str", "trim") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Trim leading and trailing whitespace.",
        ),
        ("str", "lower") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Convert text to lowercase.",
        ),
        ("str", "upper") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Convert text to uppercase.",
        ),
        ("str", "length") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Count Unicode scalar values.",
        ),
        ("str", "contains") => sig(
            namespace,
            function,
            &["value", "needle"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text contains a fragment.",
        ),
        ("str", "equals") => sig(
            namespace,
            function,
            &["value", "other"],
            &[],
            StdlibReturnKind::Bool,
            "Compare two strings exactly.",
        ),
        ("str", "startsWith") => sig(
            namespace,
            function,
            &["value", "prefix"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text starts with a prefix.",
        ),
        ("str", "endsWith") => sig(
            namespace,
            function,
            &["value", "suffix"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text ends with a suffix.",
        ),
        ("str", "truncate") => sig(
            namespace,
            function,
            &["value", "max"],
            &[],
            StdlibReturnKind::String,
            "Truncate text to a bounded number of Unicode scalar values.",
        ),
        ("str", "replace") => sig(
            namespace,
            function,
            &["value", "from", "to"],
            &[],
            StdlibReturnKind::String,
            "Replace all literal matches.",
        ),
        ("str", "split") => sig(
            namespace,
            function,
            &["value", "delimiter"],
            &["limit"],
            StdlibReturnKind::Array,
            "Split text into an array.",
        ),
        ("str", "join") => sig(
            namespace,
            function,
            &["values"],
            &["delimiter"],
            StdlibReturnKind::String,
            "Join array values into text.",
        ),
        _ => return None,
    };
    Some(signature)
}
