use crate::{StdlibReturnKind, StdlibSignature};

const NAMESPACES: &[&str] = &[
    "str", "math", "parse", "url", "csv", "sort", "list", "json", "date", "id",
];

pub fn namespaces() -> &'static [&'static str] {
    NAMESPACES
}

pub fn is_stdlib_namespace(value: &str) -> bool {
    namespaces().contains(&value)
}

pub fn is_stdlib_function(value: &str) -> bool {
    value
        .split_once('.')
        .and_then(|(namespace, function)| signature(namespace, function))
        .is_some()
}

pub fn signatures() -> Vec<StdlibSignature> {
    let mut output = Vec::new();
    for namespace in namespaces() {
        for function in functions(namespace) {
            if let Some(signature) = signature(namespace, function) {
                output.push(signature);
            }
        }
    }
    output
}

pub fn functions(namespace: &str) -> &'static [&'static str] {
    match namespace {
        "str" => &[
            "trim",
            "lower",
            "upper",
            "length",
            "contains",
            "startsWith",
            "endsWith",
            "replace",
            "split",
            "join",
        ],
        "math" => &[
            "add", "sub", "mul", "div", "round", "floor", "ceil", "abs", "min", "max", "sum",
            "average",
        ],
        "parse" => &["int", "float", "bool", "json", "string", "svg"],
        "url" => &["encode", "decode", "parse", "queryGet", "querySet"],
        "csv" => &["parse", "stringify"],
        "sort" => &["asc", "desc", "by"],
        "list" => &[
            "take",
            "skip",
            "first",
            "last",
            "count",
            "filterEquals",
            "filterContains",
            "mapField",
            "sumBy",
            "averageBy",
        ],
        "json" => &["get", "set", "pick", "omit", "merge", "stringify", "parse"],
        "date" => &["now", "formatIso", "addDays", "diffDays"],
        "id" => &["ulid"],
        _ => &[],
    }
}

pub fn signature(namespace: &str, function: &str) -> Option<StdlibSignature> {
    let signature = match (namespace, function) {
        ("str", "trim") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Trim leading and trailing whitespace.",
        ),
        ("str", "lower") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Convert text to lowercase.",
        ),
        ("str", "upper") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Convert text to uppercase.",
        ),
        ("str", "length") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Count Unicode scalar values.",
        ),
        ("str", "contains") => sig(
            namespace,
            function,
            &["value", "needle"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text contains a fragment.",
        ),
        ("str", "startsWith") => sig(
            namespace,
            function,
            &["value", "prefix"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text starts with a prefix.",
        ),
        ("str", "endsWith") => sig(
            namespace,
            function,
            &["value", "suffix"],
            &[],
            StdlibReturnKind::Bool,
            "Check whether text ends with a suffix.",
        ),
        ("str", "replace") => sig(
            namespace,
            function,
            &["value", "from", "to"],
            &[],
            StdlibReturnKind::String,
            "Replace all literal matches.",
        ),
        ("str", "split") => sig(
            namespace,
            function,
            &["value", "delimiter"],
            &["limit"],
            StdlibReturnKind::Array,
            "Split text into an array.",
        ),
        ("str", "join") => sig(
            namespace,
            function,
            &["values"],
            &["delimiter"],
            StdlibReturnKind::String,
            "Join array values into text.",
        ),
        ("math", "add") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Add two finite numbers.",
        ),
        ("math", "sub") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Subtract two finite numbers.",
        ),
        ("math", "mul") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Multiply two finite numbers.",
        ),
        ("math", "div") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Divide two finite numbers.",
        ),
        ("math", "round") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Round a finite number.",
        ),
        ("math", "floor") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Floor a finite number.",
        ),
        ("math", "ceil") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Ceil a finite number.",
        ),
        ("math", "abs") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Return the absolute value.",
        ),
        ("math", "min") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the minimum numeric value or null.",
        ),
        ("math", "max") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the maximum numeric value or null.",
        ),
        ("math", "sum") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Number,
            "Sum numeric array values.",
        ),
        ("math", "average") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Average numeric array values or null.",
        ),
        ("parse", "int") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Parse an integer or return fallback/null.",
        ),
        ("parse", "float") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Parse a finite number or return fallback/null.",
        ),
        ("parse", "bool") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Parse a boolean or return fallback/null.",
        ),
        ("parse", "json") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Parse JSON text or return fallback/null.",
        ),
        ("parse", "string") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Convert a value to string.",
        ),
        ("parse", "svg") => sig(
            namespace,
            function,
            &["value"],
            &["fallback", "colors", "format"],
            StdlibReturnKind::Unknown,
            "Convert portable SVG XML into Dowe source or normalized preview data.",
        ),
        ("url", "encode") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Percent-encode text.",
        ),
        ("url", "decode") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Percent-decode text.",
        ),
        ("url", "parse") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Object,
            "Parse URL text into serializable parts.",
        ),
        ("url", "queryGet") => sig(
            namespace,
            function,
            &["value", "name"],
            &[],
            StdlibReturnKind::Unknown,
            "Read a query parameter.",
        ),
        ("url", "querySet") => sig(
            namespace,
            function,
            &["value", "name", "param"],
            &[],
            StdlibReturnKind::String,
            "Set a query parameter.",
        ),
        ("csv", "parse") => sig(
            namespace,
            function,
            &["value"],
            &["delimiter", "header", "maxRows", "maxColumns"],
            StdlibReturnKind::Object,
            "Parse CSV text into rows.",
        ),
        ("csv", "stringify") => sig(
            namespace,
            function,
            &["rows"],
            &["delimiter"],
            StdlibReturnKind::String,
            "Serialize rows to CSV text.",
        ),
        ("sort", "asc") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Array,
            "Stable ascending sort.",
        ),
        ("sort", "desc") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Array,
            "Stable descending sort.",
        ),
        ("sort", "by") => sig(
            namespace,
            function,
            &["values", "field"],
            &["direction", "nulls"],
            StdlibReturnKind::Array,
            "Stable sort objects by a field.",
        ),
        ("list", "take") => sig(
            namespace,
            function,
            &["values", "count"],
            &[],
            StdlibReturnKind::Array,
            "Take the first items.",
        ),
        ("list", "skip") => sig(
            namespace,
            function,
            &["values", "count"],
            &[],
            StdlibReturnKind::Array,
            "Skip the first items.",
        ),
        ("list", "first") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the first item or null.",
        ),
        ("list", "last") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the last item or null.",
        ),
        ("list", "count") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Number,
            "Count array items.",
        ),
        ("list", "filterEquals") => sig(
            namespace,
            function,
            &["values", "field", "value"],
            &[],
            StdlibReturnKind::Array,
            "Filter objects by exact field value.",
        ),
        ("list", "filterContains") => sig(
            namespace,
            function,
            &["values", "field", "value"],
            &[],
            StdlibReturnKind::Array,
            "Filter objects by text containment.",
        ),
        ("list", "mapField") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Array,
            "Project one field from each object.",
        ),
        ("list", "sumBy") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Number,
            "Sum numeric object field values.",
        ),
        ("list", "averageBy") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Unknown,
            "Average numeric object field values or null.",
        ),
        ("json", "get") => sig(
            namespace,
            function,
            &["value", "path"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Read a JSON-compatible path.",
        ),
        ("json", "set") => sig(
            namespace,
            function,
            &["value", "path", "next"],
            &[],
            StdlibReturnKind::Object,
            "Return an object with a path set.",
        ),
        ("json", "pick") => sig(
            namespace,
            function,
            &["value", "fields"],
            &[],
            StdlibReturnKind::Object,
            "Pick object fields.",
        ),
        ("json", "omit") => sig(
            namespace,
            function,
            &["value", "fields"],
            &[],
            StdlibReturnKind::Object,
            "Omit object fields.",
        ),
        ("json", "merge") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Object,
            "Merge two objects shallowly.",
        ),
        ("json", "stringify") => sig(
            namespace,
            function,
            &["value"],
            &["pretty"],
            StdlibReturnKind::String,
            "Serialize JSON-compatible value.",
        ),
        ("json", "parse") => sig(
            namespace,
            function,
            &["value"],
            &["fallback"],
            StdlibReturnKind::Unknown,
            "Parse JSON text or return fallback/null.",
        ),
        ("date", "now") => sig(
            namespace,
            function,
            &[],
            &[],
            StdlibReturnKind::String,
            "Return the current UTC instant.",
        ),
        ("date", "formatIso") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::String,
            "Normalize an ISO-like instant string.",
        ),
        ("date", "addDays") => sig(
            namespace,
            function,
            &["value", "days"],
            &[],
            StdlibReturnKind::Unknown,
            "Add days to an ISO instant.",
        ),
        ("date", "diffDays") => sig(
            namespace,
            function,
            &["start", "end"],
            &[],
            StdlibReturnKind::Number,
            "Return whole-day difference.",
        ),
        ("id", "ulid") => sig(
            namespace,
            function,
            &[],
            &[],
            StdlibReturnKind::String,
            "Generate a canonical server-only ULID.",
        ),
        _ => return None,
    };
    Some(signature)
}

fn sig(
    namespace: &str,
    function: &str,
    required: &'static [&'static str],
    optional: &'static [&'static str],
    return_kind: StdlibReturnKind,
    description: &'static str,
) -> StdlibSignature {
    StdlibSignature {
        namespace: namespace.to_string(),
        function: function.to_string(),
        required,
        optional,
        return_kind,
        description,
    }
}
