fn signature_list(namespace: &str, function: &str) -> Option<StdlibSignature> {
    let signature = match (namespace, function) {
        ("list", "take") => sig(
            namespace,
            function,
            &["values", "count"],
            &[],
            StdlibReturnKind::Array,
            "Take the first items.",
        ),
        ("list", "skip") => sig(
            namespace,
            function,
            &["values", "count"],
            &[],
            StdlibReturnKind::Array,
            "Skip the first items.",
        ),
        ("list", "first") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the first item or null.",
        ),
        ("list", "last") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the last item or null.",
        ),
        ("list", "count") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Number,
            "Count array items.",
        ),
        ("list", "filterEquals") => sig(
            namespace,
            function,
            &["values", "field", "value"],
            &[],
            StdlibReturnKind::Array,
            "Filter objects by exact field value.",
        ),
        ("list", "filterContains") => sig(
            namespace,
            function,
            &["values", "field", "value"],
            &[],
            StdlibReturnKind::Array,
            "Filter objects by text containment.",
        ),
        ("list", "filterContainsAny") => sig(
            namespace,
            function,
            &["values", "field", "needles"],
            &[],
            StdlibReturnKind::Array,
            "Filter object rows when a field contains any bounded text needle.",
        ),
        ("list", "concat") => sig(
            namespace,
            function,
            &["values", "other"],
            &[],
            StdlibReturnKind::Array,
            "Concatenate two arrays without mutating either source.",
        ),
        ("list", "mapField") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Array,
            "Project one field from each object.",
        ),
        ("list", "sumBy") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Number,
            "Sum numeric object field values.",
        ),
        ("list", "averageBy") => sig(
            namespace,
            function,
            &["values", "field"],
            &[],
            StdlibReturnKind::Unknown,
            "Average numeric object field values or null.",
        ),
        _ => return None,
    };
    Some(signature)
}
