fn signature_math(namespace: &str, function: &str) -> Option<StdlibSignature> {
    let signature = match (namespace, function) {
        ("math", "add") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Add two finite numbers.",
        ),
        ("math", "sub") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Subtract two finite numbers.",
        ),
        ("math", "mul") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Multiply two finite numbers.",
        ),
        ("math", "div") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Number,
            "Divide two finite numbers.",
        ),
        ("math", "gt") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Bool,
            "Compare two finite numbers.",
        ),
        ("math", "gte") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Bool,
            "Compare two finite numbers inclusively.",
        ),
        ("math", "lt") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Bool,
            "Compare two finite numbers.",
        ),
        ("math", "lte") => sig(
            namespace,
            function,
            &["left", "right"],
            &[],
            StdlibReturnKind::Bool,
            "Compare two finite numbers inclusively.",
        ),
        ("math", "round") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Round a finite number.",
        ),
        ("math", "floor") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Floor a finite number.",
        ),
        ("math", "ceil") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Ceil a finite number.",
        ),
        ("math", "abs") => sig(
            namespace,
            function,
            &["value"],
            &[],
            StdlibReturnKind::Number,
            "Return the absolute value.",
        ),
        ("math", "min") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the minimum numeric value or null.",
        ),
        ("math", "max") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Return the maximum numeric value or null.",
        ),
        ("math", "sum") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Number,
            "Sum numeric array values.",
        ),
        ("math", "average") => sig(
            namespace,
            function,
            &["values"],
            &[],
            StdlibReturnKind::Unknown,
            "Average numeric array values or null.",
        ),
        _ => return None,
    };
    Some(signature)
}
