#[allow(dead_code)]
const OPENAI_CODEX_MODELS: &[AgentModelDefinition] = &[
    AgentModelDefinition {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
            tools: None,
            images: None,
            context_window: None,
    },
    AgentModelDefinition {
        id: "gpt-5.4",
        name: "GPT-5.4",
            tools: None,
            images: None,
            context_window: None,
    },
    AgentModelDefinition {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
            tools: None,
            images: None,
            context_window: None,
    },
    AgentModelDefinition {
        id: "gpt-5.5",
        name: "GPT-5.5",
            tools: None,
            images: None,
            context_window: None,
    },
    AgentModelDefinition {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
            tools: None,
            images: None,
            context_window: None
    },
    AgentModelDefinition {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
            tools: None,
            images: None,
            context_window: None
    },
    AgentModelDefinition {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
            tools: None,
            images: None,
            context_window: None
    },
    AgentModelDefinition {
        id: "gpt-6-astra",
        name: "GPT-6 Astra",
            tools: None,
            images: None,
            context_window: None
    },
];

const PROVIDER_IDS: &[&str] = &[
    "amazon-bedrock",
    "anthropic",
    "azure-openai-responses",
    "cloudflare-ai-gateway",
    "cloudflare-workers-ai",
    "deepseek",
    "fireworks",
    "github-copilot",
    "google",
    "google-vertex",
    "groq",
    "kimi-coding",
    "minimax",
    "minimax-cn",
    "mistral",
    "nvidia",
    "openai",
    "openai-codex",
    "opencode",
    "opencode-go",
    "openrouter",
    "qwen-token-plan",
    "qwen-token-plan-cn",
    "qwen-token-plan-individual",
    "vercel-ai-gateway",
    "xai",
    "zai",
    "zai-coding-cn",
];

pub fn builtin_provider_ids() -> &'static [&'static str] {
    PROVIDER_IDS
}

pub fn provider_definition(id: &str) -> Option<AgentProviderDefinition> {
    let definition = match id {
        "amazon-bedrock" => definition(
            "amazon-bedrock",
            "Amazon Bedrock",
            &["AWS_BEARER_TOKEN_BEDROCK"],
            &[],
            Some("https://bedrock-runtime.us-east-1.amazonaws.com"),
            "anthropic.claude-3-5-sonnet-20241022-v2:0",
            AgentProviderProtocol::BedrockConverse,
            true,
            false,
        ),
        "anthropic" => definition(
            "anthropic",
            "Anthropic",
            &[
                "ANTHROPIC_AUTH_TOKEN",
                "ANTHROPIC_OAUTH_TOKEN",
                "ANTHROPIC_API_KEY",
            ],
            &[],
            Some("https://api.anthropic.com"),
            "claude-sonnet-4-5",
            AgentProviderProtocol::AnthropicMessages,
            true,
            true,
        ),
        "azure-openai-responses" => definition(
            "azure-openai-responses",
            "Azure OpenAI",
            &["AZURE_OPENAI_API_KEY"],
            &["AZURE_OPENAI_BASE_URL"],
            None,
            "gpt-4o",
            AgentProviderProtocol::OpenAiResponses,
            true,
            false,
        ),
        "cloudflare-ai-gateway" => definition(
            "cloudflare-ai-gateway",
            "Cloudflare AI Gateway",
            &["CLOUDFLARE_API_KEY"],
            &["CLOUDFLARE_ACCOUNT_ID", "CLOUDFLARE_GATEWAY_ID"],
            Some(
                "https://gateway.ai.cloudflare.com/v1/{CLOUDFLARE_ACCOUNT_ID}/{CLOUDFLARE_GATEWAY_ID}",
            ),
            "gpt-4o",
            AgentProviderProtocol::OpenAiResponses,
            true,
            false,
        ),
        "cloudflare-workers-ai" => definition(
            "cloudflare-workers-ai",
            "Cloudflare Workers AI",
            &["CLOUDFLARE_API_KEY"],
            &["CLOUDFLARE_ACCOUNT_ID"],
            Some("https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1"),
            "@cf/deepseek-ai/deepseek-v4-flash-0731",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "deepseek" => definition(
            "deepseek",
            "DeepSeek",
            &["DEEPSEEK_API_KEY"],
            &[],
            Some("https://api.deepseek.com"),
            "deepseek-v4-flash",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "fireworks" => definition(
            "fireworks",
            "Fireworks",
            &["FIREWORKS_API_KEY"],
            &[],
            Some("https://api.fireworks.ai/inference"),
            "accounts/fireworks/models/deepseek-v4-flash-0731",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "github-copilot" => definition(
            "github-copilot",
            "GitHub Copilot",
            &["COPILOT_GITHUB_TOKEN"],
            &[],
            Some("https://api.individual.githubcopilot.com"),
            "claude-sonnet-4-5",
            AgentProviderProtocol::AnthropicMessages,
            true,
            true,
        ),
        "google" => definition(
            "google",
            "Google",
            &["GEMINI_API_KEY"],
            &[],
            Some("https://generativelanguage.googleapis.com/v1beta"),
            "gemini-2.5-flash",
            AgentProviderProtocol::GoogleGenerativeAi,
            true,
            false,
        ),
        "google-vertex" => definition(
            "google-vertex",
            "Google Vertex AI",
            &["GOOGLE_CLOUD_API_KEY"],
            &[],
            Some("https://{location}-aiplatform.googleapis.com"),
            "gemini-2.5-flash",
            AgentProviderProtocol::GoogleVertex,
            true,
            false,
        ),
        "groq" => definition(
            "groq",
            "Groq",
            &["GROQ_API_KEY"],
            &[],
            Some("https://api.groq.com/openai/v1"),
            "llama-3.1-8b-instant",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "kimi-coding" => definition(
            "kimi-coding",
            "Kimi For Coding",
            &["KIMI_API_KEY"],
            &[],
            Some("https://api.kimi.com/coding"),
            "k3",
            AgentProviderProtocol::AnthropicMessages,
            true,
            true,
        ),
        "minimax" => definition(
            "minimax",
            "MiniMax",
            &["MINIMAX_API_KEY"],
            &[],
            Some("https://api.minimax.io/anthropic"),
            "MiniMax-M2.7",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "minimax-cn" => definition(
            "minimax-cn",
            "MiniMax CN",
            &["MINIMAX_CN_API_KEY"],
            &[],
            Some("https://api.minimaxi.com/anthropic"),
            "MiniMax-M2.7",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "mistral" => definition(
            "mistral",
            "Mistral",
            &["MISTRAL_API_KEY"],
            &[],
            Some("https://api.mistral.ai/v1"),
            "mistral-large-latest",
            AgentProviderProtocol::MistralConversations,
            true,
            false,
        ),
        "nvidia" => definition(
            "nvidia",
            "NVIDIA",
            &["NVIDIA_API_KEY"],
            &[],
            Some("https://integrate.api.nvidia.com/v1"),
            "deepseek-ai/deepseek-v4-flash-0731",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "openai" => definition(
            "openai",
            "OpenAI",
            &["OPENAI_API_KEY"],
            &[],
            Some("https://api.openai.com/v1"),
            "gpt-5.5",
            AgentProviderProtocol::OpenAiResponses,
            true,
            false,
        ),
        "openai-codex" => definition(
            "openai-codex",
            "OpenAI Codex",
            &[],
            &[],
            Some("https://chatgpt.com/backend-api"),
            "gpt-5.5",
            AgentProviderProtocol::OpenAiResponses,
            false,
            true,
        ),
        "opencode" => definition(
            "opencode",
            "OpenCode Zen",
            &["OPENCODE_API_KEY"],
            &[],
            Some("https://opencode.ai/zen"),
            "claude-sonnet-4-5",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "opencode-go" => definition(
            "opencode-go",
            "OpenCode Go",
            &["OPENCODE_API_KEY"],
            &[],
            Some("https://opencode.ai/zen/go"),
            "minimax-m3",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "openrouter" => definition(
            "openrouter",
            "OpenRouter",
            &["OPENROUTER_API_KEY"],
            &[],
            Some("https://openrouter.ai/api/v1"),
            "openai/gpt-5.5",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            true,
        ),
        "qwen-token-plan" => definition(
            "qwen-token-plan",
            "Qwen Token Plan",
            &["QWEN_TOKEN_PLAN_API_KEY"],
            &[],
            Some("https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"),
            "MiniMax-M2.5",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "qwen-token-plan-cn" => definition(
            "qwen-token-plan-cn",
            "Qwen Token Plan CN",
            &["QWEN_TOKEN_PLAN_CN_API_KEY"],
            &[],
            Some("https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1"),
            "MiniMax-M2.5",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "qwen-token-plan-individual" => definition(
            "qwen-token-plan-individual",
            "Qwen Token Plan Individual",
            &["QWEN_TOKEN_PLAN_API_KEY"],
            &[],
            Some("https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"),
            "deepseek-v4-flash-0731",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "vercel-ai-gateway" => definition(
            "vercel-ai-gateway",
            "Vercel AI Gateway",
            &["AI_GATEWAY_API_KEY"],
            &[],
            Some("https://ai-gateway.vercel.sh"),
            "anthropic/claude-sonnet-4-5",
            AgentProviderProtocol::AnthropicMessages,
            true,
            false,
        ),
        "xai" => definition(
            "xai",
            "xAI",
            &["XAI_API_KEY"],
            &[],
            Some("https://api.x.ai/v1"),
            "grok-4.3",
            AgentProviderProtocol::OpenAiResponses,
            true,
            true,
        ),
        "zai" => definition(
            "zai",
            "Z.AI",
            &["ZAI_API_KEY"],
            &[],
            Some("https://api.z.ai/api/coding/paas/v4"),
            "glm-4.7",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        "zai-coding-cn" => definition(
            "zai-coding-cn",
            "Z.AI Coding CN",
            &["ZAI_CODING_CN_API_KEY"],
            &[],
            Some("https://open.bigmodel.cn/api/coding/paas/v4"),
            "glm-4.6v",
            AgentProviderProtocol::OpenAiCompletions,
            true,
            false,
        ),
        _ => return None,
    };
    Some(definition)
}

