fn dev_activity_header() -> &'static str {
    r#"package dev.dowe.generated;

import android.app.Activity;
import android.app.PictureInPictureParams;
import android.animation.ValueAnimator;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Insets;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.BlurMaskFilter;
import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Outline;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.os.Build;
import android.os.Bundle;
import android.os.SystemClock;
import android.os.Handler;
import android.os.Looper;
import android.util.LruCache;
import android.util.Rational;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewOutlineProvider;
import android.view.animation.PathInterpolator;
import android.view.ContextThemeWrapper;
import android.view.Window;
import android.view.WindowInsets;
import android.webkit.WebView;
import android.webkit.WebResourceRequest;
import android.webkit.WebViewClient;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.PopupWindow;
import android.widget.TextView;
import android.widget.VideoView;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.File;
import java.io.FileOutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.WeakHashMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;
import org.json.JSONArray;
import org.json.JSONObject;

@SuppressWarnings({"unchecked", "deprecation"})
public class DoweDevActivity extends ContextThemeWrapper {
    private static final int DOWE_JUSTIFY_START = 0;
    private static final int DOWE_JUSTIFY_CENTER = 1;
    private static final int DOWE_JUSTIFY_END = 2;
    private static final int DOWE_JUSTIFY_BETWEEN = 3;
    private static final int DOWE_JUSTIFY_AROUND = 4;
    private static final int DOWE_JUSTIFY_EVENLY = 5;
    private static final int DOWE_ALIGN_START = 0;
    private static final int DOWE_ALIGN_CENTER = 1;
    private static final int DOWE_ALIGN_END = 2;
    private static final int DOWE_ALIGN_STRETCH = 3;
    private static final int DOWE_ALIGN_BASELINE = 4;
    private static final int DOWE_DIRECTION_ROW = 0;
    private static final int DOWE_DIRECTION_COLUMN = 1;
"#
}
