#!/usr/bin/env python3
"""Refresh the offline agent model snapshot and its generated Rust representation."""
import json
import sys
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "crates/agent/catalog/models.json"
GENERATED = ROOT / "crates/agent/catalog/generated.rs"
MODELS_DEV = "https://models.dev/api.json"
OPENROUTER = "https://openrouter.ai/api/v1/models"
KNOWN = {
    "amazon-bedrock", "anthropic", "azure-openai-responses", "cloudflare-ai-gateway",
    "cloudflare-workers-ai", "deepseek", "fireworks", "github-copilot", "google",
    "google-vertex", "groq", "kimi-coding", "minimax", "minimax-cn", "nvidia",
    "openai", "openai-codex", "opencode", "opencode-go", "openrouter", "mistral", "qwen-token-plan",
    "qwen-token-plan-cn", "qwen-token-plan-individual", "vercel-ai-gateway", "xai", "zai",
    "zai-coding-cn",
}


def fetch(url):
    request = Request(url, headers={"User-Agent": "dowe-agent-catalog-updater"})
    with urlopen(request, timeout=15) as response:
        return json.load(response)


def clean(entry, fallback_id=None):
    if not isinstance(entry, dict):
        return None
    model_id = entry.get("id") or fallback_id
    if not isinstance(model_id, str) or not model_id or any(c.isspace() or ord(c) < 32 for c in model_id):
        return None
    name = entry.get("name") or model_id
    if not isinstance(name, str) or not name.strip() or any(ord(c) < 32 for c in name):
        return None
    capabilities = {}
    if isinstance(entry.get("tool_call"), bool):
        capabilities["tools"] = entry["tool_call"]
    supported = entry.get("supported_parameters")
    if isinstance(supported, list) and all(isinstance(value, str) for value in supported):
        capabilities["tools"] = "tools" in supported
    modalities = entry.get("modalities")
    if isinstance(modalities, dict) and isinstance(modalities.get("input"), list):
        capabilities["images"] = "image" in modalities["input"]
    architecture = entry.get("architecture")
    if isinstance(architecture, dict) and isinstance(architecture.get("input_modalities"), list):
        capabilities["images"] = "image" in architecture["input_modalities"]
    context_length = entry.get("context_length")
    context_window = context_length if isinstance(context_length, int) and context_length > 0 else None
    result = {"id": model_id, "name": name, "capabilities": capabilities}
    if context_window is not None:
        result["contextWindow"] = context_window
    return result


def normalize(entries):
    if isinstance(entries, dict) and isinstance(entries.get("models"), (list, dict)):
        entries = entries["models"]
    if isinstance(entries, dict):
        values = (clean(value, key) for key, value in entries.items())
    elif isinstance(entries, list):
        values = (clean(value) for value in entries)
    else:
        return []
    unique = {item["id"]: item for item in values if item}
    return [unique[model_id] for model_id in sorted(unique)]


def render_model(item):
    capabilities = item.get("capabilities", {})
    tools = f"Some({json.dumps(capabilities['tools'])})" if "tools" in capabilities else "None"
    images = f"Some({json.dumps(capabilities['images'])})" if "images" in capabilities else "None"
    context_window = item.get("contextWindow")
    context = f"Some({context_window})" if isinstance(context_window, int) and context_window > 0 else "None"
    return f"model!({json.dumps(item['id'], ensure_ascii=False)}, {json.dumps(item['name'], ensure_ascii=False)}, {tools}, {images}, {context})"


def render_generated(providers):
    aliases = {"google-vertex": "GOOGLE", "minimax-cn": "MINIMAX", "qwen-token-plan-cn": "QWEN_TOKEN_PLAN"}
    lines = [
        "// @generated by scripts/update-agent-model-catalog.py; do not edit by hand.",
        "use crate::provider::AgentModelDefinition;", "",
        "macro_rules! model { ($id:literal, $name:literal, $tools:expr, $images:expr, $context_window:expr) => { AgentModelDefinition { id: $id, name: $name, tools: $tools, images: $images, context_window: $context_window } }; }", "",
    ]
    for provider in sorted(KNOWN):
        const = provider.upper().replace("-", "_")
        if provider in aliases:
            lines.append(f"pub const {const}: &[AgentModelDefinition] = {aliases[provider]};")
            continue
        rendered = ", ".join(render_model(item) for item in providers.get(provider, []))
        lines.append(f"pub const {const}: &[AgentModelDefinition] = &[{rendered}];")
    return "\n".join(lines) + "\n"


def main():
    if "--render-only" in sys.argv[1:]:
        snapshot = json.loads(OUT.read_text())
        GENERATED.write_text(render_generated(snapshot["providers"]))
        print(f"wrote {GENERATED}")
        return 0
    try:
        models_dev, openrouter = fetch(MODELS_DEV), fetch(OPENROUTER)
    except Exception as error:
        print(f"catalog update failed (snapshot unchanged): {error}", file=sys.stderr)
        return 1
    try:
        existing = json.loads(OUT.read_text())
    except (OSError, json.JSONDecodeError):
        existing = {"providers": {}}
    providers = {key: normalize(value) for key, value in existing.get("providers", {}).items() if key in KNOWN}
    maintained = {
        (provider, item["id"]): item.get("contextWindow")
        for provider, entries in providers.items()
        for item in entries
        if isinstance(item.get("contextWindow"), int) and item["contextWindow"] > 0
    }
    if isinstance(models_dev, dict):
        for provider, entries in models_dev.items():
            if provider in KNOWN:
                models = normalize(entries)
                if models:
                    for item in models:
                        if "contextWindow" not in item and (provider, item["id"]) in maintained:
                            item["contextWindow"] = maintained[(provider, item["id"])]
                    providers[provider] = models
    if isinstance(openrouter, dict):
        models = normalize(openrouter.get("data", []))
        if models:
            for item in models:
                if "contextWindow" not in item and ("openrouter", item["id"]) in maintained:
                    item["contextWindow"] = maintained[("openrouter", item["id"])]
            providers["openrouter"] = models
    snapshot = {"schemaVersion": 1, "generatedBy": "scripts/update-agent-model-catalog.py", "sources": [MODELS_DEV, OPENROUTER], "providers": {key: providers.get(key, []) for key in sorted(KNOWN)}}
    OUT.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n")
    GENERATED.write_text(render_generated(snapshot["providers"]))
    print(f"wrote {OUT} and {GENERATED}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
