// @generated by scripts/update-agent-model-catalog.py; do not edit by hand.
use crate::provider::AgentModelDefinition;

macro_rules! model { ($id:literal, $name:literal, $tools:expr, $images:expr, $context_window:expr) => { AgentModelDefinition { id: $id, name: $name, tools: $tools, images: $images, context_window: $context_window } }; }

pub const AMAZON_BEDROCK: &[AgentModelDefinition] = &[model!("anthropic.claude-3-5-sonnet-20241022-v2:0", "Claude 3.5 Sonnet", None, None, None)];
pub const ANTHROPIC: &[AgentModelDefinition] = &[model!("claude-sonnet-4-5", "Claude Sonnet 4.5", None, None, None)];
pub const AZURE_OPENAI_RESPONSES: &[AgentModelDefinition] = &[model!("gpt-4o", "GPT-4o", None, None, None)];
pub const CLOUDFLARE_AI_GATEWAY: &[AgentModelDefinition] = &[model!("gpt-4o", "GPT-4o", None, None, None)];
pub const CLOUDFLARE_WORKERS_AI: &[AgentModelDefinition] = &[model!("@cf/deepseek-ai/deepseek-v4-flash-0731", "DeepSeek V4 Flash", None, None, None)];
pub const DEEPSEEK: &[AgentModelDefinition] = &[model!("deepseek-v4-flash", "DeepSeek V4 Flash", None, None, None)];
pub const FIREWORKS: &[AgentModelDefinition] = &[model!("accounts/fireworks/models/deepseek-v4-flash-0731", "DeepSeek V4 Flash", None, None, None)];
pub const GITHUB_COPILOT: &[AgentModelDefinition] = &[model!("claude-sonnet-4-5", "Claude Sonnet 4.5", None, None, None)];
pub const GOOGLE: &[AgentModelDefinition] = &[model!("gemini-2.5-flash", "Gemini 2.5 Flash", None, None, None)];
pub const GOOGLE_VERTEX: &[AgentModelDefinition] = GOOGLE;
pub const GROQ: &[AgentModelDefinition] = &[model!("llama-3.1-8b-instant", "Llama 3.1 8B Instant", None, None, None)];
pub const KIMI_CODING: &[AgentModelDefinition] = &[model!("k3", "Kimi K3", None, None, None)];
pub const MINIMAX: &[AgentModelDefinition] = &[model!("MiniMax-M2.7", "MiniMax M2.7", None, None, None)];
pub const MINIMAX_CN: &[AgentModelDefinition] = MINIMAX;
pub const MISTRAL: &[AgentModelDefinition] = &[model!("mistral-large-latest", "Mistral Large", None, None, None)];
pub const NVIDIA: &[AgentModelDefinition] = &[model!("deepseek-ai/deepseek-v4-flash-0731", "DeepSeek V4 Flash", None, None, None)];
pub const OPENAI: &[AgentModelDefinition] = &[model!("gpt-5.5", "GPT-5.5", None, None, None)];
pub const OPENAI_CODEX: &[AgentModelDefinition] = &[model!("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", None, None, None), model!("gpt-5.4", "GPT-5.4", None, None, None), model!("gpt-5.4-mini", "GPT-5.4 mini", None, None, None), model!("gpt-5.5", "GPT-5.5", None, None, None), model!("gpt-5.6-luna", "GPT-5.6 Luna", None, None, None), model!("gpt-5.6-sol", "GPT-5.6 Sol", None, None, None), model!("gpt-5.6-terra", "GPT-5.6 Terra", None, None, None), model!("gpt-6-astra", "GPT-6 Astra", None, None, None)];
pub const OPENCODE: &[AgentModelDefinition] = &[model!("claude-sonnet-4-5", "Claude Sonnet 4.5", None, None, None)];
pub const OPENCODE_GO: &[AgentModelDefinition] = &[model!("minimax-m3", "MiniMax M3", None, None, None)];
pub const OPENROUTER: &[AgentModelDefinition] = &[model!("anthropic/claude-sonnet-4-5", "Claude Sonnet 4.5", Some(true), Some(true), None), model!("deepseek/deepseek-v4-flash", "DeepSeek V4 Flash", Some(true), Some(false), Some(1000000)), model!("google/gemini-2.5-flash", "Gemini 2.5 Flash", Some(true), Some(true), None), model!("openai/gpt-5.5", "GPT-5.5", Some(true), Some(true), None)];
pub const QWEN_TOKEN_PLAN: &[AgentModelDefinition] = &[model!("MiniMax-M2.5", "MiniMax M2.5", None, None, None)];
pub const QWEN_TOKEN_PLAN_CN: &[AgentModelDefinition] = QWEN_TOKEN_PLAN;
pub const QWEN_TOKEN_PLAN_INDIVIDUAL: &[AgentModelDefinition] = &[model!("deepseek-v4-flash-0731", "DeepSeek V4 Flash", None, None, None)];
pub const VERCEL_AI_GATEWAY: &[AgentModelDefinition] = &[model!("anthropic/claude-sonnet-4-5", "Claude Sonnet 4.5", None, None, None)];
pub const XAI: &[AgentModelDefinition] = &[model!("grok-4.3", "Grok 4.3", None, None, None)];
pub const ZAI: &[AgentModelDefinition] = &[model!("glm-4.7", "GLM 4.7", None, None, None)];
pub const ZAI_CODING_CN: &[AgentModelDefinition] = &[model!("glm-4.6v", "GLM 4.6V", None, None, None)];
