#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhoneCountry {
    pub code: &'static str,
    pub name: &'static str,
    pub dial: &'static str,
}

static PHONE_COUNTRIES: &[PhoneCountry] = &[
    PhoneCountry { code: "AF", name: "Afghanistan (افغانستان‎)", dial: "93" },
    PhoneCountry { code: "AL", name: "Albania (Shqipëri)", dial: "355" },
    PhoneCountry { code: "DZ", name: "Algeria (الجزائر‎)", dial: "213" },
    PhoneCountry { code: "AS", name: "American Samoa", dial: "1" },
    PhoneCountry { code: "AD", name: "Andorra", dial: "376" },
    PhoneCountry { code: "AO", name: "Angola", dial: "244" },
    PhoneCountry { code: "AI", name: "Anguilla", dial: "1" },
    PhoneCountry { code: "AG", name: "Antigua and Barbuda", dial: "1" },
    PhoneCountry { code: "AR", name: "Argentina", dial: "54" },
    PhoneCountry { code: "AM", name: "Armenia (Հայաստան)", dial: "374" },
    PhoneCountry { code: "AW", name: "Aruba", dial: "297" },
    PhoneCountry { code: "AC", name: "Ascension Island", dial: "247" },
    PhoneCountry { code: "AU", name: "Australia", dial: "61" },
    PhoneCountry { code: "AT", name: "Austria (Österreich)", dial: "43" },
    PhoneCountry { code: "AZ", name: "Azerbaijan (Azərbaycan)", dial: "994" },
    PhoneCountry { code: "BS", name: "Bahamas", dial: "1" },
    PhoneCountry { code: "BH", name: "Bahrain (البحرين‎)", dial: "973" },
    PhoneCountry { code: "BD", name: "Bangladesh (বাংলাদেশ)", dial: "880" },
    PhoneCountry { code: "BB", name: "Barbados", dial: "1" },
    PhoneCountry { code: "BY", name: "Belarus (Беларусь)", dial: "375" },
    PhoneCountry { code: "BE", name: "Belgium (België)", dial: "32" },
    PhoneCountry { code: "BZ", name: "Belize", dial: "501" },
    PhoneCountry { code: "BJ", name: "Benin (Bénin)", dial: "229" },
    PhoneCountry { code: "BM", name: "Bermuda", dial: "1" },
    PhoneCountry { code: "BT", name: "Bhutan (འབྲུག)", dial: "975" },
    PhoneCountry { code: "BO", name: "Bolivia", dial: "591" },
    PhoneCountry { code: "BA", name: "Bosnia and Herzegovina (Босна и Херцеговина)", dial: "387" },
    PhoneCountry { code: "BW", name: "Botswana", dial: "267" },
    PhoneCountry { code: "BR", name: "Brazil (Brasil)", dial: "55" },
    PhoneCountry { code: "IO", name: "British Indian Ocean Territory", dial: "246" },
    PhoneCountry { code: "VG", name: "British Virgin Islands", dial: "1" },
    PhoneCountry { code: "BN", name: "Brunei", dial: "673" },
    PhoneCountry { code: "BG", name: "Bulgaria (България)", dial: "359" },
    PhoneCountry { code: "BF", name: "Burkina Faso", dial: "226" },
    PhoneCountry { code: "BI", name: "Burundi (Uburundi)", dial: "257" },
    PhoneCountry { code: "KH", name: "Cambodia (កម្ពុជា)", dial: "855" },
    PhoneCountry { code: "CM", name: "Cameroon (Cameroun)", dial: "237" },
    PhoneCountry { code: "CV", name: "Cape Verde (Kabu Verdi)", dial: "238" },
    PhoneCountry { code: "BQ", name: "Caribbean Netherlands", dial: "599" },
    PhoneCountry { code: "KY", name: "Cayman Islands", dial: "1" },
    PhoneCountry { code: "CF", name: "Central African Republic (République centrafricaine)", dial: "236" },
    PhoneCountry { code: "TD", name: "Chad (Tchad)", dial: "235" },
    PhoneCountry { code: "CL", name: "Chile", dial: "56" },
    PhoneCountry { code: "CN", name: "China (中国)", dial: "86" },
    PhoneCountry { code: "CX", name: "Christmas Island", dial: "61" },
    PhoneCountry { code: "CC", name: "Cocos (Keeling) Islands", dial: "61" },
    PhoneCountry { code: "CO", name: "Colombia", dial: "57" },
    PhoneCountry { code: "KM", name: "Comoros (جزر القمر‎)", dial: "269" },
    PhoneCountry { code: "CD", name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)", dial: "243" },
    PhoneCountry { code: "CG", name: "Congo (Republic) (Congo-Brazzaville)", dial: "242" },
    PhoneCountry { code: "CK", name: "Cook Islands", dial: "682" },
    PhoneCountry { code: "CR", name: "Costa Rica", dial: "506" },
    PhoneCountry { code: "CI", name: "Côte d’Ivoire", dial: "225" },
    PhoneCountry { code: "HR", name: "Croatia (Hrvatska)", dial: "385" },
    PhoneCountry { code: "CU", name: "Cuba", dial: "53" },
    PhoneCountry { code: "CW", name: "Curaçao", dial: "599" },
    PhoneCountry { code: "CY", name: "Cyprus (Κύπρος)", dial: "357" },
    PhoneCountry { code: "CZ", name: "Czech Republic (Česká republika)", dial: "420" },
    PhoneCountry { code: "DK", name: "Denmark (Danmark)", dial: "45" },
    PhoneCountry { code: "DJ", name: "Djibouti", dial: "253" },
    PhoneCountry { code: "DM", name: "Dominica", dial: "1" },
    PhoneCountry { code: "DO", name: "Dominican Republic (República Dominicana)", dial: "1" },
    PhoneCountry { code: "EC", name: "Ecuador", dial: "593" },
    PhoneCountry { code: "EG", name: "Egypt (مصر‎)", dial: "20" },
    PhoneCountry { code: "SV", name: "El Salvador", dial: "503" },
    PhoneCountry { code: "GQ", name: "Equatorial Guinea (Guinea Ecuatorial)", dial: "240" },
    PhoneCountry { code: "ER", name: "Eritrea", dial: "291" },
    PhoneCountry { code: "EE", name: "Estonia (Eesti)", dial: "372" },
    PhoneCountry { code: "SZ", name: "Eswatini", dial: "268" },
    PhoneCountry { code: "ET", name: "Ethiopia", dial: "251" },
    PhoneCountry { code: "FK", name: "Falkland Islands (Islas Malvinas)", dial: "500" },
    PhoneCountry { code: "FO", name: "Faroe Islands (Føroyar)", dial: "298" },
    PhoneCountry { code: "FJ", name: "Fiji", dial: "679" },
    PhoneCountry { code: "FI", name: "Finland (Suomi)", dial: "358" },
    PhoneCountry { code: "FR", name: "France", dial: "33" },
    PhoneCountry { code: "GF", name: "French Guiana (Guyane française)", dial: "594" },
    PhoneCountry { code: "PF", name: "French Polynesia (Polynésie française)", dial: "689" },
    PhoneCountry { code: "GA", name: "Gabon", dial: "241" },
    PhoneCountry { code: "GM", name: "Gambia", dial: "220" },
    PhoneCountry { code: "GE", name: "Georgia (საქართველო)", dial: "995" },
    PhoneCountry { code: "DE", name: "Germany (Deutschland)", dial: "49" },
    PhoneCountry { code: "GH", name: "Ghana (Gaana)", dial: "233" },
    PhoneCountry { code: "GI", name: "Gibraltar", dial: "350" },
    PhoneCountry { code: "GR", name: "Greece (Ελλάδα)", dial: "30" },
    PhoneCountry { code: "GL", name: "Greenland (Kalaallit Nunaat)", dial: "299" },
    PhoneCountry { code: "GD", name: "Grenada", dial: "1" },
    PhoneCountry { code: "GP", name: "Guadeloupe", dial: "590" },
    PhoneCountry { code: "GU", name: "Guam", dial: "1" },
    PhoneCountry { code: "GT", name: "Guatemala", dial: "502" },
    PhoneCountry { code: "GG", name: "Guernsey", dial: "44" },
    PhoneCountry { code: "GN", name: "Guinea (Guinée)", dial: "224" },
    PhoneCountry { code: "GW", name: "Guinea-Bissau (Guiné Bissau)", dial: "245" },
    PhoneCountry { code: "GY", name: "Guyana", dial: "592" },
    PhoneCountry { code: "HT", name: "Haiti", dial: "509" },
    PhoneCountry { code: "HN", name: "Honduras", dial: "504" },
    PhoneCountry { code: "HK", name: "Hong Kong (香港)", dial: "852" },
    PhoneCountry { code: "HU", name: "Hungary (Magyarország)", dial: "36" },
    PhoneCountry { code: "IS", name: "Iceland (Ísland)", dial: "354" },
    PhoneCountry { code: "IN", name: "India (भारत)", dial: "91" },
    PhoneCountry { code: "ID", name: "Indonesia", dial: "62" },
    PhoneCountry { code: "IR", name: "Iran (ایران‎)", dial: "98" },
    PhoneCountry { code: "IQ", name: "Iraq (العراق‎)", dial: "964" },
    PhoneCountry { code: "IE", name: "Ireland", dial: "353" },
    PhoneCountry { code: "IM", name: "Isle of Man", dial: "44" },
    PhoneCountry { code: "IL", name: "Israel (ישראל‎)", dial: "972" },
    PhoneCountry { code: "IT", name: "Italy (Italia)", dial: "39" },
    PhoneCountry { code: "JM", name: "Jamaica", dial: "1" },
    PhoneCountry { code: "JP", name: "Japan (日本)", dial: "81" },
    PhoneCountry { code: "JE", name: "Jersey", dial: "44" },
    PhoneCountry { code: "JO", name: "Jordan (الأردن‎)", dial: "962" },
    PhoneCountry { code: "KZ", name: "Kazakhstan (Казахстан)", dial: "7" },
    PhoneCountry { code: "KE", name: "Kenya", dial: "254" },
    PhoneCountry { code: "KI", name: "Kiribati", dial: "686" },
    PhoneCountry { code: "XK", name: "Kosovo", dial: "383" },
    PhoneCountry { code: "KW", name: "Kuwait (الكويت‎)", dial: "965" },
    PhoneCountry { code: "KG", name: "Kyrgyzstan (Кыргызстан)", dial: "996" },
    PhoneCountry { code: "LA", name: "Laos (ລາວ)", dial: "856" },
    PhoneCountry { code: "LV", name: "Latvia (Latvija)", dial: "371" },
    PhoneCountry { code: "LB", name: "Lebanon (لبنان‎)", dial: "961" },
    PhoneCountry { code: "LS", name: "Lesotho", dial: "266" },
    PhoneCountry { code: "LR", name: "Liberia", dial: "231" },
    PhoneCountry { code: "LY", name: "Libya (ليبيا‎)", dial: "218" },
    PhoneCountry { code: "LI", name: "Liechtenstein", dial: "423" },
    PhoneCountry { code: "LT", name: "Lithuania (Lietuva)", dial: "370" },
    PhoneCountry { code: "LU", name: "Luxembourg", dial: "352" },
    PhoneCountry { code: "MO", name: "Macau (澳門)", dial: "853" },
    PhoneCountry { code: "MK", name: "North Macedonia (Македонија)", dial: "389" },
    PhoneCountry { code: "MG", name: "Madagascar (Madagasikara)", dial: "261" },
    PhoneCountry { code: "MW", name: "Malawi", dial: "265" },
    PhoneCountry { code: "MY", name: "Malaysia", dial: "60" },
    PhoneCountry { code: "MV", name: "Maldives", dial: "960" },
    PhoneCountry { code: "ML", name: "Mali", dial: "223" },
    PhoneCountry { code: "MT", name: "Malta", dial: "356" },
    PhoneCountry { code: "MH", name: "Marshall Islands", dial: "692" },
    PhoneCountry { code: "MQ", name: "Martinique", dial: "596" },
    PhoneCountry { code: "MR", name: "Mauritania (موريتانيا‎)", dial: "222" },
    PhoneCountry { code: "MU", name: "Mauritius (Moris)", dial: "230" },
    PhoneCountry { code: "YT", name: "Mayotte", dial: "262" },
    PhoneCountry { code: "MX", name: "Mexico (México)", dial: "52" },
    PhoneCountry { code: "FM", name: "Micronesia", dial: "691" },
    PhoneCountry { code: "MD", name: "Moldova (Republica Moldova)", dial: "373" },
    PhoneCountry { code: "MC", name: "Monaco", dial: "377" },
    PhoneCountry { code: "MN", name: "Mongolia (Монгол)", dial: "976" },
    PhoneCountry { code: "ME", name: "Montenegro (Crna Gora)", dial: "382" },
    PhoneCountry { code: "MS", name: "Montserrat", dial: "1" },
    PhoneCountry { code: "MA", name: "Morocco (المغرب‎)", dial: "212" },
    PhoneCountry { code: "MZ", name: "Mozambique (Moçambique)", dial: "258" },
    PhoneCountry { code: "MM", name: "Myanmar (Burma) (မြန်မာ)", dial: "95" },
    PhoneCountry { code: "NA", name: "Namibia (Namibië)", dial: "264" },
    PhoneCountry { code: "NR", name: "Nauru", dial: "674" },
    PhoneCountry { code: "NP", name: "Nepal (नेपाल)", dial: "977" },
    PhoneCountry { code: "NL", name: "Netherlands (Nederland)", dial: "31" },
    PhoneCountry { code: "NC", name: "New Caledonia (Nouvelle-Calédonie)", dial: "687" },
    PhoneCountry { code: "NZ", name: "New Zealand", dial: "64" },
    PhoneCountry { code: "NI", name: "Nicaragua", dial: "505" },
    PhoneCountry { code: "NE", name: "Niger (Nijar)", dial: "227" },
    PhoneCountry { code: "NG", name: "Nigeria", dial: "234" },
    PhoneCountry { code: "NU", name: "Niue", dial: "683" },
    PhoneCountry { code: "NF", name: "Norfolk Island", dial: "672" },
    PhoneCountry { code: "KP", name: "North Korea (조선 민주주의 인민 공화국)", dial: "850" },
    PhoneCountry { code: "MP", name: "Northern Mariana Islands", dial: "1" },
    PhoneCountry { code: "NO", name: "Norway (Norge)", dial: "47" },
    PhoneCountry { code: "OM", name: "Oman (عُمان‎)", dial: "968" },
    PhoneCountry { code: "PK", name: "Pakistan (پاکستان‎)", dial: "92" },
    PhoneCountry { code: "PW", name: "Palau", dial: "680" },
    PhoneCountry { code: "PS", name: "Palestine (فلسطين‎)", dial: "970" },
    PhoneCountry { code: "PA", name: "Panama (Panamá)", dial: "507" },
    PhoneCountry { code: "PG", name: "Papua New Guinea", dial: "675" },
    PhoneCountry { code: "PY", name: "Paraguay", dial: "595" },
    PhoneCountry { code: "PE", name: "Peru (Perú)", dial: "51" },
    PhoneCountry { code: "PH", name: "Philippines", dial: "63" },
    PhoneCountry { code: "PL", name: "Poland (Polska)", dial: "48" },
    PhoneCountry { code: "PT", name: "Portugal", dial: "351" },
    PhoneCountry { code: "PR", name: "Puerto Rico", dial: "1" },
    PhoneCountry { code: "QA", name: "Qatar (قطر‎)", dial: "974" },
    PhoneCountry { code: "RE", name: "Réunion (La Réunion)", dial: "262" },
    PhoneCountry { code: "RO", name: "Romania (România)", dial: "40" },
    PhoneCountry { code: "RU", name: "Russia (Россия)", dial: "7" },
    PhoneCountry { code: "RW", name: "Rwanda", dial: "250" },
    PhoneCountry { code: "BL", name: "Saint Barthélemy", dial: "590" },
    PhoneCountry { code: "SH", name: "Saint Helena", dial: "290" },
    PhoneCountry { code: "KN", name: "Saint Kitts and Nevis", dial: "1" },
    PhoneCountry { code: "LC", name: "Saint Lucia", dial: "1" },
    PhoneCountry { code: "MF", name: "Saint Martin (Saint-Martin (partie française))", dial: "590" },
    PhoneCountry { code: "PM", name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", dial: "508" },
    PhoneCountry { code: "VC", name: "Saint Vincent and the Grenadines", dial: "1" },
    PhoneCountry { code: "WS", name: "Samoa", dial: "685" },
    PhoneCountry { code: "SM", name: "San Marino", dial: "378" },
    PhoneCountry { code: "ST", name: "São Tomé and Príncipe (São Tomé e Príncipe)", dial: "239" },
    PhoneCountry { code: "SA", name: "Saudi Arabia (المملكة العربية السعودية‎)", dial: "966" },
    PhoneCountry { code: "SN", name: "Senegal (Sénégal)", dial: "221" },
    PhoneCountry { code: "RS", name: "Serbia (Србија)", dial: "381" },
    PhoneCountry { code: "SC", name: "Seychelles", dial: "248" },
    PhoneCountry { code: "SL", name: "Sierra Leone", dial: "232" },
    PhoneCountry { code: "SG", name: "Singapore", dial: "65" },
    PhoneCountry { code: "SX", name: "Sint Maarten", dial: "1" },
    PhoneCountry { code: "SK", name: "Slovakia (Slovensko)", dial: "421" },
    PhoneCountry { code: "SI", name: "Slovenia (Slovenija)", dial: "386" },
    PhoneCountry { code: "SB", name: "Solomon Islands", dial: "677" },
    PhoneCountry { code: "SO", name: "Somalia (Soomaaliya)", dial: "252" },
    PhoneCountry { code: "ZA", name: "South Africa", dial: "27" },
    PhoneCountry { code: "KR", name: "South Korea (대한민국)", dial: "82" },
    PhoneCountry { code: "SS", name: "South Sudan (جنوب السودان‎)", dial: "211" },
    PhoneCountry { code: "ES", name: "Spain (España)", dial: "34" },
    PhoneCountry { code: "LK", name: "Sri Lanka (ශ්‍රී ලංකාව)", dial: "94" },
    PhoneCountry { code: "SD", name: "Sudan (السودان‎)", dial: "249" },
    PhoneCountry { code: "SR", name: "Suriname", dial: "597" },
    PhoneCountry { code: "SJ", name: "Svalbard and Jan Mayen", dial: "47" },
    PhoneCountry { code: "SE", name: "Sweden (Sverige)", dial: "46" },
    PhoneCountry { code: "CH", name: "Switzerland (Schweiz)", dial: "41" },
    PhoneCountry { code: "SY", name: "Syria (سوريا‎)", dial: "963" },
    PhoneCountry { code: "TW", name: "Taiwan (台灣)", dial: "886" },
    PhoneCountry { code: "TJ", name: "Tajikistan", dial: "992" },
    PhoneCountry { code: "TZ", name: "Tanzania", dial: "255" },
    PhoneCountry { code: "TH", name: "Thailand (ไทย)", dial: "66" },
    PhoneCountry { code: "TL", name: "Timor-Leste", dial: "670" },
    PhoneCountry { code: "TG", name: "Togo", dial: "228" },
    PhoneCountry { code: "TK", name: "Tokelau", dial: "690" },
    PhoneCountry { code: "TO", name: "Tonga", dial: "676" },
    PhoneCountry { code: "TT", name: "Trinidad and Tobago", dial: "1" },
    PhoneCountry { code: "TA", name: "Tristan da Cunha", dial: "290" },
    PhoneCountry { code: "TN", name: "Tunisia (تونس‎)", dial: "216" },
    PhoneCountry { code: "TR", name: "Turkey (Türkiye)", dial: "90" },
    PhoneCountry { code: "TM", name: "Turkmenistan", dial: "993" },
    PhoneCountry { code: "TC", name: "Turks and Caicos Islands", dial: "1" },
    PhoneCountry { code: "TV", name: "Tuvalu", dial: "688" },
    PhoneCountry { code: "VI", name: "U.S. Virgin Islands", dial: "1" },
    PhoneCountry { code: "UG", name: "Uganda", dial: "256" },
    PhoneCountry { code: "UA", name: "Ukraine (Україна)", dial: "380" },
    PhoneCountry { code: "AE", name: "United Arab Emirates (الإمارات العربية المتحدة‎)", dial: "971" },
    PhoneCountry { code: "GB", name: "United Kingdom", dial: "44" },
    PhoneCountry { code: "US", name: "United States", dial: "1" },
    PhoneCountry { code: "UY", name: "Uruguay", dial: "598" },
    PhoneCountry { code: "UZ", name: "Uzbekistan (Oʻzbekiston)", dial: "998" },
    PhoneCountry { code: "VU", name: "Vanuatu", dial: "678" },
    PhoneCountry { code: "VA", name: "Vatican City (Città del Vaticano)", dial: "39" },
    PhoneCountry { code: "VE", name: "Venezuela", dial: "58" },
    PhoneCountry { code: "VN", name: "Vietnam (Việt Nam)", dial: "84" },
    PhoneCountry { code: "WF", name: "Wallis and Futuna (Wallis-et-Futuna)", dial: "681" },
    PhoneCountry { code: "EH", name: "Western Sahara (الصحراء الغربية‎)", dial: "212" },
    PhoneCountry { code: "YE", name: "Yemen (اليمن‎)", dial: "967" },
    PhoneCountry { code: "ZM", name: "Zambia", dial: "260" },
    PhoneCountry { code: "ZW", name: "Zimbabwe", dial: "263" },
    PhoneCountry { code: "AX", name: "Åland Islands", dial: "358" },
];

pub fn phone_countries() -> &'static [PhoneCountry] {
    PHONE_COUNTRIES
}

pub fn phone_country(code: Option<&str>) -> Option<PhoneCountry> {
    let code = code?;
    PHONE_COUNTRIES
        .iter()
        .copied()
        .find(|country| country.code.eq_ignore_ascii_case(code))
}

pub fn ordered_phone_countries(
    selected: Option<&str>,
    priority: &[String],
) -> Vec<PhoneCountry> {
    let selected = selected.and_then(|code| phone_country(Some(code)));
    let mut countries = Vec::with_capacity(PHONE_COUNTRIES.len());
    if let Some(country) = selected {
        countries.push(country);
    }
    for code in priority {
        if let Some(country) = phone_country(Some(code)) {
            if !countries.iter().any(|item| item.code == country.code) {
                countries.push(country);
            }
        }
    }
    for country in PHONE_COUNTRIES {
        if !countries.iter().any(|item| item.code == country.code) {
            countries.push(*country);
        }
    }
    countries
}

pub fn phone_country_flag_icon(code: &str) -> Option<SideNavIcon> {
    country_flag_icon(code)
}
