#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinComponent {
    Box,
    Section,
    Flex,
    Grid,
    Input,
    Select,
    Option,
    Code,
    Video,
    Iframe,
    Device,
    Canvas,
    Candlestick,
    ArcChart,
    AreaChart,
    BarChart,
    LineChart,
    PieChart,
    Table,
    Divider,
    Button,
    Brand,
    Banner,
    IconButton,
    ToggleTheme,
    SelectTheme,
    Fab,
    FabAction,
    Slider,
    Dropzone,
    ComboBox,
    ComboOption,
    CsvField,
    CsvColumn,
    DragDrop,
    DragGroup,
    DragItem,
    Editor,
    ImageCropper,
    Password,
    Phone,
    Pin,
    Textarea,
    Alert,
    Icon,
    Svg,
    Path,
    AppBar,
    Footer,
    BottomBar,
    NavMenu,
    SideNav,
    RailNav,
    Sidebar,
    Scaffold,
    Splash,
    Drawer,
    Avatar,
    Badge,
    Chip,
    Skeleton,
    Modal,
    AlertDialog,
    Tooltip,
    Toast,
    Dropdown,
    Command,
    AvatarGroup,
    ChatBox,
    Empty,
    Marquee,
    TypeWriter,
    RichText,
    Record,
    ToggleGroup,
    Collapsible,
    Countdown,
    Map,
    Audio,
    Image,
    Accordion,
    Carousel,
    Checkbox,
    Color,
    Date,
    DateRange,
    RadioGroup,
    Toggle,
    Card,
    Tabs,
    Tab,
    Stepper,
    Step,
    Title,
    Text,
}

impl BuiltinComponent {
    pub const ALL: &'static [Self] = &[
        Self::Box,
        Self::Section,
        Self::Flex,
        Self::Grid,
        Self::Input,
        Self::Select,
        Self::Option,
        Self::Code,
        Self::Video,
        Self::Iframe,
        Self::Device,
        Self::Canvas,
        Self::Candlestick,
        Self::ArcChart,
        Self::AreaChart,
        Self::BarChart,
        Self::LineChart,
        Self::PieChart,
        Self::Table,
        Self::Divider,
        Self::Button,
        Self::Brand,
        Self::Banner,
        Self::IconButton,
        Self::ToggleTheme,
        Self::SelectTheme,
        Self::Fab,
        Self::FabAction,
        Self::Slider,
        Self::Dropzone,
        Self::ComboBox,
        Self::ComboOption,
        Self::CsvField,
        Self::CsvColumn,
        Self::DragDrop,
        Self::DragGroup,
        Self::DragItem,
        Self::Editor,
        Self::ImageCropper,
        Self::Password,
        Self::Phone,
        Self::Pin,
        Self::Textarea,
        Self::Alert,
        Self::Icon,
        Self::Svg,
        Self::Path,
        Self::AppBar,
        Self::Footer,
        Self::BottomBar,
        Self::NavMenu,
        Self::SideNav,
        Self::RailNav,
        Self::Sidebar,
        Self::Scaffold,
        Self::Splash,
        Self::Drawer,
        Self::Avatar,
        Self::Badge,
        Self::Chip,
        Self::Skeleton,
        Self::Modal,
        Self::AlertDialog,
        Self::Tooltip,
        Self::Toast,
        Self::Dropdown,
        Self::Command,
        Self::AvatarGroup,
        Self::ChatBox,
        Self::Empty,
        Self::Marquee,
        Self::TypeWriter,
        Self::RichText,
        Self::Record,
        Self::ToggleGroup,
        Self::Collapsible,
        Self::Countdown,
        Self::Map,
        Self::Audio,
        Self::Image,
        Self::Accordion,
        Self::Carousel,
        Self::Checkbox,
        Self::Color,
        Self::Date,
        Self::DateRange,
        Self::RadioGroup,
        Self::Toggle,
        Self::Card,
        Self::Tabs,
        Self::Tab,
        Self::Stepper,
        Self::Step,
        Self::Title,
        Self::Text,
    ];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "Box" => Some(Self::Box),
            "Section" => Some(Self::Section),
            "Flex" => Some(Self::Flex),
            "Grid" => Some(Self::Grid),
            "Input" => Some(Self::Input),
            "Select" => Some(Self::Select),
            "Option" => Some(Self::Option),
            "Code" => Some(Self::Code),
            "Video" => Some(Self::Video),
            "Iframe" => Some(Self::Iframe),
            "Device" => Some(Self::Device),
            "Canvas" => Some(Self::Canvas),
            "Candlestick" => Some(Self::Candlestick),
            "ArcChart" => Some(Self::ArcChart),
            "AreaChart" => Some(Self::AreaChart),
            "BarChart" => Some(Self::BarChart),
            "LineChart" => Some(Self::LineChart),
            "PieChart" => Some(Self::PieChart),
            "Table" => Some(Self::Table),
            "Divider" => Some(Self::Divider),
            "Button" => Some(Self::Button),
            "Brand" => Some(Self::Brand),
            "Banner" => Some(Self::Banner),
            "IconButton" => Some(Self::IconButton),
            "ToggleTheme" => Some(Self::ToggleTheme),
            "SelectTheme" => Some(Self::SelectTheme),
            "Fab" => Some(Self::Fab),
            "fabAction" => Some(Self::FabAction),
            "Slider" => Some(Self::Slider),
            "Dropzone" => Some(Self::Dropzone),
            "ComboBox" => Some(Self::ComboBox),
            "comboOption" => Some(Self::ComboOption),
            "CsvField" => Some(Self::CsvField),
            "csvColumn" => Some(Self::CsvColumn),
            "DragDrop" => Some(Self::DragDrop),
            "dragGroup" => Some(Self::DragGroup),
            "dragItem" => Some(Self::DragItem),
            "Editor" => Some(Self::Editor),
            "ImageCropper" => Some(Self::ImageCropper),
            "Password" => Some(Self::Password),
            "Phone" => Some(Self::Phone),
            "Pin" => Some(Self::Pin),
            "Textarea" => Some(Self::Textarea),
            "Alert" => Some(Self::Alert),
            "Icon" => Some(Self::Icon),
            "Svg" => Some(Self::Svg),
            "Path" => Some(Self::Path),
            "AppBar" => Some(Self::AppBar),
            "Footer" => Some(Self::Footer),
            "BottomBar" => Some(Self::BottomBar),
            "NavMenu" => Some(Self::NavMenu),
            "SideNav" => Some(Self::SideNav),
            "RailNav" => Some(Self::RailNav),
            "Sidebar" => Some(Self::Sidebar),
            "Scaffold" => Some(Self::Scaffold),
            "Splash" => Some(Self::Splash),
            "Drawer" => Some(Self::Drawer),
            "Avatar" => Some(Self::Avatar),
            "Badge" => Some(Self::Badge),
            "Chip" => Some(Self::Chip),
            "Skeleton" => Some(Self::Skeleton),
            "Modal" => Some(Self::Modal),
            "AlertDialog" => Some(Self::AlertDialog),
            "Tooltip" => Some(Self::Tooltip),
            "Toast" => Some(Self::Toast),
            "Dropdown" => Some(Self::Dropdown),
            "Command" => Some(Self::Command),
            "AvatarGroup" => Some(Self::AvatarGroup),
            "ChatBox" => Some(Self::ChatBox),
            "Empty" => Some(Self::Empty),
            "Marquee" => Some(Self::Marquee),
            "TypeWriter" => Some(Self::TypeWriter),
            "RichText" => Some(Self::RichText),
            "Record" => Some(Self::Record),
            "ToggleGroup" => Some(Self::ToggleGroup),
            "Collapsible" => Some(Self::Collapsible),
            "Countdown" => Some(Self::Countdown),
            "Map" => Some(Self::Map),
            "Audio" => Some(Self::Audio),
            "Image" => Some(Self::Image),
            "Accordion" => Some(Self::Accordion),
            "Carousel" => Some(Self::Carousel),
            "Checkbox" => Some(Self::Checkbox),
            "Color" => Some(Self::Color),
            "Date" => Some(Self::Date),
            "DateRange" => Some(Self::DateRange),
            "RadioGroup" => Some(Self::RadioGroup),
            "Toggle" => Some(Self::Toggle),
            "Card" => Some(Self::Card),
            "Tabs" => Some(Self::Tabs),
            "tab" => Some(Self::Tab),
            "Stepper" => Some(Self::Stepper),
            "step" => Some(Self::Step),
            "Title" => Some(Self::Title),
            "Text" => Some(Self::Text),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Box => "Box",
            Self::Section => "Section",
            Self::Flex => "Flex",
            Self::Grid => "Grid",
            Self::Input => "Input",
            Self::Select => "Select",
            Self::Option => "Option",
            Self::Code => "Code",
            Self::Video => "Video",
            Self::Iframe => "Iframe",
            Self::Device => "Device",
            Self::Canvas => "Canvas",
            Self::Candlestick => "Candlestick",
            Self::ArcChart => "ArcChart",
            Self::AreaChart => "AreaChart",
            Self::BarChart => "BarChart",
            Self::LineChart => "LineChart",
            Self::PieChart => "PieChart",
            Self::Table => "Table",
            Self::Divider => "Divider",
            Self::Button => "Button",
            Self::Brand => "Brand",
            Self::Banner => "Banner",
            Self::IconButton => "IconButton",
            Self::ToggleTheme => "ToggleTheme",
            Self::SelectTheme => "SelectTheme",
            Self::Fab => "Fab",
            Self::FabAction => "fabAction",
            Self::Slider => "Slider",
            Self::Dropzone => "Dropzone",
            Self::ComboBox => "ComboBox",
            Self::ComboOption => "comboOption",
            Self::CsvField => "CsvField",
            Self::CsvColumn => "csvColumn",
            Self::DragDrop => "DragDrop",
            Self::DragGroup => "dragGroup",
            Self::DragItem => "dragItem",
            Self::Editor => "Editor",
            Self::ImageCropper => "ImageCropper",
            Self::Password => "Password",
            Self::Phone => "Phone",
            Self::Pin => "Pin",
            Self::Textarea => "Textarea",
            Self::Alert => "Alert",
            Self::Icon => "Icon",
            Self::Svg => "Svg",
            Self::Path => "Path",
            Self::AppBar => "AppBar",
            Self::Footer => "Footer",
            Self::BottomBar => "BottomBar",
            Self::NavMenu => "NavMenu",
            Self::SideNav => "SideNav",
            Self::RailNav => "RailNav",
            Self::Sidebar => "Sidebar",
            Self::Scaffold => "Scaffold",
            Self::Splash => "Splash",
            Self::Drawer => "Drawer",
            Self::Avatar => "Avatar",
            Self::Badge => "Badge",
            Self::Chip => "Chip",
            Self::Skeleton => "Skeleton",
            Self::Modal => "Modal",
            Self::AlertDialog => "AlertDialog",
            Self::Tooltip => "Tooltip",
            Self::Toast => "Toast",
            Self::Dropdown => "Dropdown",
            Self::Command => "Command",
            Self::AvatarGroup => "AvatarGroup",
            Self::ChatBox => "ChatBox",
            Self::Empty => "Empty",
            Self::Marquee => "Marquee",
            Self::TypeWriter => "TypeWriter",
            Self::RichText => "RichText",
            Self::Record => "Record",
            Self::ToggleGroup => "ToggleGroup",
            Self::Collapsible => "Collapsible",
            Self::Countdown => "Countdown",
            Self::Map => "Map",
            Self::Audio => "Audio",
            Self::Image => "Image",
            Self::Accordion => "Accordion",
            Self::Carousel => "Carousel",
            Self::Checkbox => "Checkbox",
            Self::Color => "Color",
            Self::Date => "Date",
            Self::DateRange => "DateRange",
            Self::RadioGroup => "RadioGroup",
            Self::Toggle => "Toggle",
            Self::Card => "Card",
            Self::Tabs => "Tabs",
            Self::Tab => "tab",
            Self::Stepper => "Stepper",
            Self::Step => "step",
            Self::Title => "Title",
            Self::Text => "Text",
        }
    }
}
